name: Run Colab Notebook

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install yfinance pandas numpy plotly talib matplotlib

      - name: Run the notebook
        run: |
          jupyter nbconvert --to notebook --execute Estrategia_USDPEN.ipynb --output-dir=output
