name: Run Colab Notebook

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yfinance pandas numpy plotly ta matplotlib jupyter

      - name: Create output directory
        run: |
          mkdir -p output  # Crea la carpeta output si no existe

      - name: Run the notebook and capture output
        run: |
          # Captura la fecha y hora actual en formato YYYY-MM-DD_HH-MM-SS
          fecha_hora=$(date +'%Y-%m-%d_%H-%M-%S')
          # Ejecuta el notebook y redirige la salida a un archivo
          jupyter nbconvert --to notebook --execute Estrategia_USDPEN.ipynb --output-dir=output --allow-errors
          # Verifica si se creó el archivo de salida y renómbralo
          mv output/Estrategia_USDPEN.ipynb output/"resultados_$fecha_hora.ipynb"

      - name: Commit and push results to resultados branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          # Verifica si el branch 'resultados' ya existe
          if git show-ref --verify --quiet refs/heads/resultados; then
            git checkout resultados  # Si existe, simplemente cámbiate a él
          else
            git checkout -b resultados  # Si no existe, créalo
          fi
          
          # Copia el archivo de resultados a la raíz
          cp output/"resultados_*.ipynb" .  # Copia el archivo con la fecha y hora
          git add resultados_*.ipynb
          git commit -m "Agregar resultados de ejecución del notebook"
          git push -u origin resultados  # Haz push al branch 'resultados'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
