name: Run Notebook

on:
  schedule:
    - cron: '30 * * * *'  # Ejecuta todos los días a cada hora en el minuto 0
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Chequear el repositorio
    - name: Check out the repository
      uses: actions/checkout@v3
      
    # Paso 2: Instalar dependencias del sistema necesarias para compilar TA-Lib
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wget

    # Paso 3: Descargar y compilar TA-Lib desde el código fuente
    - name: Install TA-Lib
      run: |
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib
        ./configure --prefix=/usr
        make
        sudo make install
        
    # Paso 4: Instalar dependencias de Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Paso 5: Instalar librerias    
    - name: Install dependencies
      run: |
        pip install numpy==1.26.4  # Versión compatible con TA-Lib
        pip install pandas jupyter nbconvert yfinance matplotlib pytz TA-Lib 

    # Paso 6: Run the notebook
    - name: Run the Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute Prueba_Github.ipynb --output output.ipynb

    # Paso 7 Subir el archivo PNG generado como artifact directamente
    - name: Upload historical_close_price.png as artifact
      uses: actions/upload-artifact@v3
      with:
        name: historical_close_price # Nombre exacto del archivo
        path: historical_close_price.png  # Ruta exacta del archivo generado

    # Paso 8: Commit and push changes using GITHUB_TOKEN
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add output.ipynb historical_close_price.png
        git commit -m "Action Corrida"
        git push origin main
