name: Run Notebook

# Este workflow se ejecutará cuando se empuje al branch 'main'
on:
  push:
    branches:
      - main

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Chequear el repositorio
    - name: Check out the repository
      uses: actions/checkout@v3

    # Paso 2: Instalar dependencias de Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install pandas jupyter nbconvert yfinance matplotlib pytz TA-Lib
        pip install pytz

    # Step 3: Run the notebook
    - name: Run the Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute Prueba_Github.ipynb --output output.ipynb

    # Step 4: Commit and push changes using GITHUB_TOKEN
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add output.ipynb historical_close_price.png
        git commit -m "Update Output"
        git push origin main
