name: Run USDPEN Strategy Daily

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del código del repositorio
    - name: Checkout code
      uses: actions/checkout@v4

    # Paso 2: Configurar Python en la versión deseada
    - name: Set up Python
      uses: actions/setup-python@v3

    # Paso 3: Instalar dependencias del sistema necesarias para TA-Lib
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libta-lib0 libta-lib0-dev

    # Paso 4: Instalar las librerías de Python (sin requirements.txt)
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib seaborn TA-Lib tabulate nbconvert jupyter

    # Paso 5: Ejecutar el Jupyter Notebook y guardar la salida
    - name: Run Jupyter Notebook and save output
      run: |
        jupyter nbconvert --to notebook --execute "GITHUB - Estrategia USDPEN.ipynb" --output output.ipynb


